# -*- coding: utf-8 -*-
"""214814455-Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O0QuOyHb_How0gQkPUEn3gJpA1uW5-Yl
"""

s = 'fullstackslp'

print(s[0])

print(s[11])

print(s[4:9])

print(s[9:])

print(s[7:10])

reversedString = '' .join(reversed(s))
print(reversedString)


l = [3,7,[5,[1,4,'hello']]]

l[2][1][2] = 'goodbye'

print(l[2][1][2])


d1 = {'simple_key':'hello'}

print(d1['simple_key'])

d2 = {'k1':{'k2':'hello'}}

print(d2['k1']['k2'])

d3 = {'k1':[{'nest_key':['this is deep',['hello']]}]}

print(d3['k1'][0]['nest_key'][1])



mylist = [1,1,1,1,1,2,2,2,2,3,3,3,3]
newList = []
for mylist in mylist:
    if mylist not in newList:
        newList.append(mylist)
print(newList)

age = 45
name = "Kyle"


"Hello my dog's name is Kyle and he looks 45 years old"
print( "Hello my dog's name is {} and he looks {} years old " .format(name,age))